### ISSUE TITLE
Not syncing stories (beside folders)

### ISSUE THREAD

**Issue by bonmedi** [storyblok/component-sync-example#1]
Any particular reason why this example is not syncing the stories/content itself?

**Comment by DominikAngerer** [comment]
This demo was created as of a live-chat request on how one would do that. 

Stories/Content are fully custom structures migrations/syncs are most of the time custom actions. However you can use the Management API to do so as well - looping through the Stories in your first Space and creating/updating them in the new Space using the slug.
